### ISSUE TITLE
Different FOVs in Shader Scopes

### ISSUE THREAD

**Issue by donizettilorenzo** [themrdemonized/STALKER-Anomaly-modded-exes#14] opened 2023-02-05 08:40 UTC
*Base Anomaly 1.5.2 installation, no other mods installed
*Deleted Shaders Folder
sds_enable ON

000_shader_placeholder.db0 is necessary? 

For the test I'm using an ACOG scope on the basic submachine gun (starting items)

**Comment by themrdemonized** [comment] 2023-02-05 12:56
readme tells to unpack everything

**Comment by donizettilorenzo** [comment] 2023-02-05 13:18
Still not working

https://postimg.cc/N9Tp3Q7C

**Comment by themrdemonized** [comment] 2023-02-05 13:39
its the 3d scope, shader scopes only applied to 2d overlays (for example svd or gauss scope). To get 2d overlays to other scopes download the mods for them, for example Scope Overlayer from DLTX Minimod Pack

**Comment by donizettilorenzo** [comment] 2023-02-05 13:55
Oh, thanks!

**Comment by donizettilorenzo** [comment] 2023-02-05 18:54
Addendum: now it works but I have a question!
The original readme says:

"The mod will automatically adjust your weapons scope_zoom_factor to compensate, so you're not "adding" any magnification on top of the scopes magnification, just adjusting the difference in FOV outside and inside the scope."

But there is :|
The "outside" FOV remains the same, it does not "scale down" to achieve the same magnification of scope_factor 1 so the "inside" FOV scale up

scope_factor 1
https://i.postimg.cc/JzRGjwQ0/Anomaly-DX11-AVX-2023-02-05-19-52-20-487.jpg

scope_factor 0.5
https://i.postimg.cc/Hs9LYZCg/Anomaly-DX11-AVX-2023-02-05-19-52-35-997.jpg

So there's something wrong here, see the "reference" image: https://media.moddb.com/images/members/5/4509/4508587/profile/factors.png

**Comment by themrdemonized** [comment] 2023-02-06 02:45
i'll see what can be done, i'm not a shader dev so the "perfect solution" is undoable for me, but the fov difference i can check

**Comment by donizettilorenzo** [comment] 2023-02-06 08:01
I can just forward the issue to the original author of the mod

**Comment by donizettilorenzo** [comment] 2023-02-22 09:11
Any news? I hope I've explained the problem (there's "too much zoom" where there must be none, the mod was originally intended to preserve the zoom level and "unzoom" the rest)

**Comment by themrdemonized** [comment] 2023-02-22 10:01
no solution to that yet

**Comment by themrdemonized** [comment] 2023-02-26 07:34
So from my tests, the problem only affected by scopes with changeable zoom levels. It works as intended with static scopes. After changing scope_factor you need to switch sights on a gun, or if its not possible, restart the save

**Comment by donizettilorenzo** [comment] 2023-02-26 08:39
And for the scopes needing the DLTX overlayer?

Il giorno dom 26 feb 2023 alle ore 08:35 themrdemonized <
***@***.***> ha scritto:

**Comment by themrdemonized** [comment] 2023-02-26 09:49
shader scopes works only on 2d overlays period

**Comment by donizettilorenzo** [comment] 2023-02-26 10:04
I mean the zoom factor. Tested and yes, it works AFTER a savegame reload! Thanks!

**Comment by donizettilorenzo** [comment] 2023-02-26 19:25
I can confirm that using a scope switching mod it's possible to obtain the same result of loading a savegame :)

That's only one last thing, as I've said before: the perfect solution for the shader is to be applied to the OUTSIDE of the scope, scaling down the frame - and not to scale up the inner part of the scope - and then blurring it!
In other words the better solution is to make it work in "reverse"

**Comment by themrdemonized** [comment] 2023-03-05 18:13
Fixed in the latest build

**Closed by themrdemonized** 2023-03-05 18:13 UTC
